version: '3.9'

services:

  mysqldb:
    image: mysql:8.0-debian
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=locker
      - MYSQL_PASSWORD=passlocker123
      - MYSQL_DATABASE=PassLockerDB
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: